#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

# https://www.habitat.sh/docs/reference/#handlebars-helpers
export JAVA_HOME={{pkgPathFor "core/jre8"}}
export TOMCAT_HOME={{pkgPathFor "core/tomcat8"}}/tc

echo "JAVA_HOME is $JAVA_HOME"
echo "TOMCAT_HOME is $TOMCAT_HOME"

cp {{pkg.path}}/*.war $TOMCAT_HOME/webapps

exec ${TOMCAT_HOME}/bin/catalina.sh run
